#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1
PROG=/usr/bin/beszel-agent

append_fs() {
    local value="$1"
    if [ -z "$FS_LIST" ]; then
        FS_LIST="$value"
    else
        FS_LIST="$FS_LIST,$value"
    fi
}

start_service() {
    local enable port key token hub_url

    config_load beszel-agent

    config_get_bool enable "main" "enable" 0
    [ "$enable" -eq 1 ] || return 0

    config_get port "main" "port" "45876"
    config_get key "main" "key" ""
    config_get token "main" "token" ""
    config_get hub_url "main" "hub_url" ""
    config_get nics "main" "nics" ""

    FS_LIST=""
    config_list_foreach "main" "extra_filesystems" append_fs

    procd_open_instance "beszel-agent"
    procd_set_param command "$PROG"

    procd_set_param env PORT="$port" HOST_PROC="/proc" HOST_SYS="/sys"

    [ -n "$key" ] && procd_append_param env KEY="$key"
    [ -n "$token" ] && procd_append_param env TOKEN="$token"
    [ -n "$hub_url" ] && procd_append_param env HUB_URL="$hub_url"
    [ -n "$FS_LIST" ] && procd_append_param env EXTRA_FILESYSTEMS="$FS_LIST"
    [ -n "$nics" ] && procd_append_param env NICS="$nics"
    
    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_set_param respawn
    procd_close_instance
}

service_triggers() {
    procd_add_reload_trigger "beszel-agent"
}

reload_service() {
    stop
    start
}
